portfolio_site/portfolio_site/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profiles.urls')),

]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

portfolio_site/profiles/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('projects/', project_view, name='project_view'),

    path('profile/', profile_view, name='profile_view'),
    path('edit-profile/', edit_profile, name='edit_profile'),
     
    path('portfolio/<int:id>/', portfolio_view, name='portfolio_view'),
    path('portfolio/', portfolio_view, name='portfolio_view'),
    path('portfolio/edit/', edit_portfolio_view, name='edit_portfolio'),
    path('add-custom-field/', add_custom_field, name='add_custom_field'),
    path('delete-custom-field/<int:field_id>/', delete_custom_field, name='delete_custom_field'),

    path('certificates/<int:id>/', certificate_detail, name='certificate_detail'),
    path('certificates/add/', certificate_add, name='certificate_add'),
    path('certificates/edit/<int:id>/', certificate_edit, name='certificate_edit'),
    path('certificates/delete/<int:id>/', certificate_delete, name='certificate_delete'),
    
    path('projects/add/', add_project, name='add_project'),
    path('projects/edit/<int:project_id>/', edit_project, name='edit_project'),
    path('projects/delete/<int:project_id>/', delete_project, name='delete_project'),
    path('projects/<int:id>/', project_detail_view, name='project_detail'),
    path('projects/<int:id>/edit_image/<int:image_id>/', edit_project_image_view, name='edit_project_image'),
    path('projects/<int:id>/delete_image/<int:image_id>/', delete_project_image_view, name='delete_project_image'),

    path('search/', search, name='search'),
    path('register/', Register_user, name='register'),
    path('login/', loginUser, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('dash/', dash_view, name='dash'),  
    path('', base_view, name='base'),

]    

portfolio_site/profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import JSONField 


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200, null=True, unique=True)
    phone = models.CharField(max_length=15, null=True)
    profile_pic = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.user.username


class Portfolio(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    skills = models.TextField(blank=True)
    education = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user_profile.user.username}'s Portfolio"

class CustomField(models.Model):
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    field_name = models.CharField(max_length=200)
    field_value = models.TextField(blank=True)
    field_image = models.ImageField(upload_to='custom_field_images/', blank=True, null=True)

    def __str__(self):
        return self.field_name

class Project(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='intern_images/', blank=True, null=True)
    link = models.URLField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class ProjectImage(models.Model):
    project = models.ForeignKey(Project, related_name='images', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=True)
    image = models.ImageField(upload_to='project_images/') 

    def __str__(self):
        return f"{self.project.title} - Image"  


class CertificateFiles(models.Model):
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    certificate_pdf = models.FileField(upload_to='certificate_pdfs/', blank=True, null=True)

portfolio_site/templates/Portfolio/add_custom_field.html
<!-- add_custom_field.html -->

{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Add Custom Field</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="{{ custom_field_form.field_name.id_for_label }}">Field Name:</label>
            {{ custom_field_form.field_name }}
        </div>
        <div class="form-group">
            <label for="{{ custom_field_form.field_value.id_for_label }}">Field Value:</label>
            {{ custom_field_form.field_value }}
        </div>
        <div class="form-group">
            <label for="{{ custom_field_form.field_image.id_for_label }}">Field Image:</label>
            {{ custom_field_form.field_image }}
        </div>
        <button type="submit" class="btn btn-primary">Add Custom Field</button>
    </form>
</div>
{% endblock %}

portfolio_site/templates/Portfolio/certificate_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Confirm Delete Certificate</h1>
    <p>Are you sure you want to delete the certificate: "{{ certificate.name }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'certificate_view' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

portfolio_site/templates/Portfolio/certificate_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container p-2">
    <h1>Certificate Detail</h1>
    <h2>{{ certificate.name }}</h2>
    <br><br>
    <p>Click the link below to view or download the certificate:</p>
    <p><a href="{{ certificate.certificate_pdf.url }}" target="_blank">View Certificate PDF</a></p>

    <div class="mt-3">
        {% if is_admin or is_intern %}
        <a href="{% url 'certificate_edit' certificate.id %}" class="btn btn-link">Edit Certificate</a>
        <form method="post" action="{% url 'certificate_delete' certificate.id %}" >
            {% csrf_token %}
            <button type="submit" class="btn btn-link text-danger">Delete Certificate</button>
        </form>
        {% endif %}
        <div style="height: 500px;">
            <embed src="{{ certificate.certificate_pdf.url }}" type="application/pdf" style="width: 100%; height: 100%;">
        </div>
    </div>
</div>

<!-- <br><br><br><br><br><br><br>
<br><br><br><br><br><br><br> -->


{% endblock %}

portfolio_site/templates/Portfolio/certificate_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>{{ form.instance.id|yesno:"Edit Certificate,Add Certificate" }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="{{ form.name.id_for_label }}">Name:</label>
            {{ form.name }}
        </div>
        <div class="form-group">
            <label for="{{ form.certificate_pdf.id_for_label }}">Certificate PDF:</label>
            {% if form.instance.certificate_pdf %}
            <div style="height: 500px;">
                <iframe src="{{ form.instance.certificate_pdf.url }}" style="width: 100%; height: 100%;" frameborder="0"></iframe>
            </div>
            {% endif %}
            {{ form.certificate_pdf }}
        </div>
        <button type="submit" class="btn btn-primary">{{ form.instance.id|yesno:"Save Changes,Add Certificate" }}</button>
    </form>
</div>
{% endblock %}

portfolio_site/templates/Portfolio/edit_portfolio.html
{% extends 'base.html' %}

{% block content %}
<div class="flex-container p-5">
    <h1 class="text-primary">Edit Portfolio</h1>
    <hr>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        

        {% if portfolio_form.errors %}
            <div class="alert alert-danger">
                <ul>
                {% for field in portfolio_form %}
                    {% for error in field.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
                </ul>
            </div>
        {% endif %}
         
        <a href="{% url 'edit_profile' %}" class="btn btn-primary">Edit User Profile</a></td></h3>
         
        <div class="card p-4">
            <div class="form-group card-body">
                <label for="{{ portfolio_form.bio.id_for_label }}">Bio:</label>
                {{ portfolio_form.bio }}
            </div>
            <div class="form-group card-body">
                <label for="{{ portfolio_form.skills.id_for_label }}">Skills:</label>
                {{ portfolio_form.skills }}
            </div>
            <div class="form-group card-body">
                <label for="{{ portfolio_form.education.id_for_label }}">Education:</label>
                {{ portfolio_form.education }}
            </div>
            

            <h3>Custom Fields</h3>
            {% if custom_fields %}
                {% for field in custom_fields %}
                    <div class="card mb-3">
                        <div class="card-body">

                            <div class="form-group">
                                <label for="id_custom_field_name_{{ field.id }}">Field Name:</label>
                                <input type="text" id="id_custom_field_name_{{ field.id }}" name="custom_field_name_{{ field.id }}" class="form-control" value="{{ field.field_name }}">
                            </div>

                            <div class="form-group">
                                <label for="id_custom_field_value_{{ field.id }}">Field Value:</label>
                                <input type="text" id="id_custom_field_value_{{ field.id }}" name="custom_field_value_{{ field.id }}" class="form-control" value="{{ field.field_value }}">
                            </div>

                            <div class="form-group">
                                <label for="id_custom_field_image_{{ field.id }}">Field Image:</label>
                                {% if field.field_image %}
                                    <img style="height: 20rem;" id="custom_field_image_preview_{{ field.id }}" src="{{ field.field_image.url }}" alt="{{ field.field_name }} image" class="img-fluid mb-2">
                                {% else %}
                                    <img style="height: 20rem;" id="custom_field_image_preview_{{ field.id }}" src="#" alt="Placeholder" class="img-fluid mb-2 d-none">
                                {% endif %}
                                <input type="file" id="id_custom_field_image_{{ field.id }}" name="custom_field_image_{{ field.id }}" class="form-control-file" onchange="previewImage(this, 'custom_field_image_preview_{{ field.id }}')">
                            </div>

                            <a href="{% url 'delete_custom_field' field.id %}" class="btn btn-sm btn-outline-danger">Delete Field</a>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p>No custom fields added yet.</p>
            {% endif %}
         </div>
        


        <p><a class="btn btn-secondary" href="{% url 'add_custom_field' %}">Add Custom Field</a></p>
        
        <button type="submit" name="save_portfolio" class="btn btn-primary">Save Portfolio</button>
    </form>
</div>

<script>
    function previewImage(input, imgId) {
        var imgElement = document.getElementById(imgId);
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function(e) {
                imgElement.src = e.target.result;
                imgElement.classList.remove('d-none'); // Show the image element
            }
            reader.readAsDataURL(input.files[0]); // Read the uploaded file as a data URL
        } else {
            imgElement.src = '#';
            imgElement.classList.add('d-none'); // Hide the image element
        }
    }
</script>

{% endblock %}

portfolio_site/templates/Portfolio/portfolio.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">

<div class="container px-0 py-2 card mb-2">
    <div class="px-2"> 
        <h2 class="text-light py-2 px-3 bg-primary">{{ portfolio.user_profile.name }}'s Portfolio</h2>
        {% if is_admin or is_intern %}
        <a class="btn btn-link btn-sm" href="{% url 'edit_portfolio' %}">Edit Portfolio</a>
        {% endif %}
        <br><br>
        

        <div class="card-group">
            <div class="card">
                <div class="card-body d-flex px-4 align-items-center">
                    <img style="height: 200px;" 
                    src="{% if profile.profile_pic %}{{ profile.profile_pic.url }}{% else %}{% static 'img/profile-img-lh.jpg' %}{% endif %}" 
                    alt="Profile Picture" class="profile-pic m-3 rounded ">
                    <div class="user-info px-5">
                        <p class="card-title"><strong>Name : </strong>{{ profile.name }}</p>
                        <p class="card-text"><strong>Skills : </strong>{{ portfolio.skills }}</p>
                        <p class="card-text"><strong>Email : </strong> {{ profile.email }}</p>
                        <p class="card-text"><strong>Phone : </strong> {{ profile.phone }}</p>
                    </div>
                </div>
            </div>
        </div>



        <div class="card-group">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><strong>Bio</strong></h5>
                    <p class="card-text">{{ portfolio.bio }}</p>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><strong>Skills</strong></h5>
                    <p class="card-text">{{ portfolio.skills }}</p>
                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><strong>Education</strong></h5>
                    <p class="card-text">{{ portfolio.education }}</p>
                </div>
            </div>
        </div>

        {% if portfolio.customfield_set.all %}
            {% for field in portfolio.customfield_set.all %}
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title"><strong>{{ field.field_name }}</strong></h5>
                        <p class="card-text">{{ field.field_value }}</p>
                        {% if field.field_image %}
                            <img style="height: 200px;" src="{{ field.field_image.url }}" alt="{{ field.field_name }} image" class="rounded float-start img-thumbnail">
                        {% endif %}
                    </div>
                </div>
             {% endfor %}
        {% endif %}
    <br>        

    <h3 class="text-primary bg-primary-outline px-2">Certificates</h3>
    <hr>
    {% if is_admin or is_intern %}
    <a href="{% url 'certificate_add' %}" class="btn btn-link">Add Certificate</a>
    {% endif %}
    <div class="row">
        {% for certificate in certificates %}
        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                    <h5>{{ certificate.name }}</h5>
                    <a href="{% url 'certificate_detail' certificate.id %}">View</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
<br>    

    <h3 class="text-primary px-2">Projects</h3>
    <hr>
    {% if is_admin or is_intern %}
    <a class="btn btn-link" href="{% url 'add_project' %}">Add New Project</a>
    {% endif %}
        <div class="card-group">
            {% for project in projects %}
            <div class="card">
                <div class="card-body">
                    <h4>{{ project.title }}</h4>
                    <p>{{ project.description }}</p>
                    <a class="btn btn-link" href="{% url 'project_detail' project.id %}">View Project</a>
                </div>
            </div>
            {% endfor %}
        </div>
    <br>
    
</div>
{% endblock %}