portfolio_site/portfolio_site/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('profiles.urls')),

]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

portfolio_site/profiles/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('projects/', project_view, name='project_view'),

    path('profile/', profile_view, name='profile_view'),
    path('edit-profile/', edit_profile, name='edit_profile'),
     
    path('portfolio/<int:id>/', portfolio_view, name='portfolio_view'),
    path('portfolio/', portfolio_view, name='portfolio_view'),
    path('portfolio/edit/', edit_portfolio_view, name='edit_portfolio'),
    path('add-custom-field/', add_custom_field, name='add_custom_field'),
    path('delete-custom-field/<int:field_id>/', delete_custom_field, name='delete_custom_field'),

    path('certificates/<int:id>/', certificate_detail, name='certificate_detail'),
    path('certificates/add/', certificate_add, name='certificate_add'),
    path('certificates/edit/<int:id>/', certificate_edit, name='certificate_edit'),
    path('certificates/delete/<int:id>/', certificate_delete, name='certificate_delete'),
    
    path('projects/add/', add_project, name='add_project'),
    path('projects/edit/<int:project_id>/', edit_project, name='edit_project'),
    path('projects/delete/<int:project_id>/', delete_project, name='delete_project'),
    path('projects/<int:id>/', project_detail_view, name='project_detail'),
    path('projects/<int:id>/edit_image/<int:image_id>/', edit_project_image_view, name='edit_project_image'),
    path('projects/<int:id>/delete_image/<int:image_id>/', delete_project_image_view, name='delete_project_image'),

    path('search/', search, name='search'),
    path('register/', Register_user, name='register'),
    path('login/', loginUser, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('dash/', dash_view, name='dash'),  
    path('', base_view, name='base'),

]    

portfolio_site/profiles/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import JSONField 


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200, null=True, unique=True)
    phone = models.CharField(max_length=15, null=True)
    profile_pic = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.user.username


class Portfolio(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    skills = models.TextField(blank=True)
    education = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user_profile.user.username}'s Portfolio"

class CustomField(models.Model):
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    field_name = models.CharField(max_length=200)
    field_value = models.TextField(blank=True)
    field_image = models.ImageField(upload_to='custom_field_images/', blank=True, null=True)

    def __str__(self):
        return self.field_name

class Project(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='intern_images/', blank=True, null=True)
    link = models.URLField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class ProjectImage(models.Model):
    project = models.ForeignKey(Project, related_name='images', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, blank=True)
    image = models.ImageField(upload_to='project_images/') 

    def __str__(self):
        return f"{self.project.title} - Image"  


class CertificateFiles(models.Model):
    portfolio = models.ForeignKey(Portfolio, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    certificate_pdf = models.FileField(upload_to='certificate_pdfs/', blank=True, null=True)

portfolio_site/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="base">
    <meta name="author" content="base">

    <title>Intern Portfolio</title>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

</html>

{% block style %}
{% endblock %}

<style>
    .image-profile {
  width: 40px; 
  height: 40px; 
  object-fit: cover; 
    }

    .container {
      display: flex;
      flex-direction: column;
      min-height: 50vh;
  }

  .footer {
      position: fixed;
      bottom: 10%;
      width: 100%;
      background-color: #f8f9fa;
      text-align: center;
      padding: 10px 0;
  }

</style>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">
        
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'dash' %}">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Intern Portfolio</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'dash' %}">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>
            {% if is_admin or is_intern %}
            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Intern </span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">{{ request.user }} Profile:</h6>
                        <a class="collapse-item" href="{% url 'portfolio_view'  %}">Portfolio</a>
                        <a class="collapse-item" href="{% url 'profile_view' %}">Profile</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Portfolio</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Portfolio</h6>
                        <a class="collapse-item" href="{% url 'project_view'  %}">View Projects</a>
                        <a class="collapse-item" href="{% url 'add_project' %}">Add Project</a>
                        <!-- <a class="collapse-item" href="{% url 'certificate_detail' certificate.id %}">Other</a> -->
                        <a class="collapse-item" href="{% url 'certificate_add' %}">Add Certiificates</a>
                    </div>
                </div>
            </li>


            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message
            <div class="sidebar-card d-none d-lg-flex">
                <img class="sidebar-card-illustration mb-2" src="{% static 'img/undraw_rocket.svg' %}" alt="...">
                <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>
                <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">Upgrade to Pro!</a>
            </div> -->
            {% endif %}
        </ul>
        
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Search -->
                    <form action="{% url 'search' %}" method="get"
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control bg-light border-0 small" placeholder="Search Interns"
                                aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="{% url 'search' %}" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search Interns" aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>


                       
                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user}}
                                    {% if request.user.userprofile.profile_pic %}
                                    <img class="image-profile rounded-circle" src="{{ request.user.userprofile.profile_pic.url }}" alt="Profile" >
                                    {% else %}
                                    <img class="image-profile rounded-circle" src="{% static 'img/profile-img-lh.jpg' %}" alt="Profile" >
                                    {% endif %}
                                </span>

                            </a>
                            
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                {% if is_admin or is_intern %}
                                <a class="dropdown-item" href="{% url 'profile_view' %}">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>

                                <a class="dropdown-item" href="{% url 'logout' %}" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            {% else %}
                            <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'login' %}" >
                                <i class="fas fa-sign-in-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                Login
                                </a>
                            {% endif %}
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                {% block content %}


            {% endblock %}
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2024</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    {% block extra_js %}
    {% endblock %}
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages -->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>

</body>

</html>

portfolio_site/templates/dash.html
{% extends 'base.html' %}
{% load static %}
{% block style %}

<style>
  .card-group {
      display: flex;
      flex-wrap: wrap;
      gap: 20px; 
  }

  .card {
      flex: 1 1 calc(33.33% - 20px);
      margin-bottom: 1px;
  }

  .card-body {
      display: flex;
      align-items: center;
  }

  .profile-pic {
      width: 100px;
      height: 100px;
      object-fit: cover;
      border-radius: 50%;
  }

  .user-info {
      display: flex;
      flex-direction: column;
      justify-content: center;
      margin-left: 20px;
  }
</style>
{% endblock %}

{% block content %}


<div class="container p-2">

  <h3>Interns</h3>
  <div class="card-group">
      {% for profile in user_profiles %}
          <div class="card">
              <div class="card-body align-items-center">
                  <img style="height : 150px;" src="{% if profile.profile_pic %}{{ profile.profile_pic.url }}{% else %}{% static 'img/profile-img-lh.jpg' %}{% endif %}" alt="Profile Picture" class="rounded">
                  <div class="user-info">
                      <h5 class="card-title">{{ profile.name }}</h5>
                      <p class="card-text"><strong>Skills:</strong>
                          {% if profile.portfolio_set.all %}
                              {% for portfolio in profile.portfolio_set.all %}
                                  {{ portfolio.skills }}
                                  {% if not forloop.last %}, {% endif %}
                              
                      </p>
                      <p class="card-text"><strong>Email:</strong> {{ profile.email }}</p>
                      <p class="card-text"><strong>Phone:</strong> {{ profile.phone }}</p>
                      <a href="{% url 'portfolio_view' portfolio.id %}" class="btn btn-link text-left">View Portfolio</a>
                      {% endfor %}
                      {% endif %}
                  </div>
              </div>
          </div>
      {% endfor %}
  </div>

  <div class="container  p-1">
    <h2 class="text-primary">Intern Project Examples</h2>
    <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-interval="3000">
      <div class="carousel-inner">
        {% for image in project_images %}
        <div class="carousel-item {% if forloop.first %}active{% endif %}">
          <h3>Project : {{ image.project.title }}</h3>
          <img src="{{ image.image.url }}" class="d-block w-100" alt="{{ image.name }}">        
        </div>
        {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>



{% block extra_js %}
<script>
  document.addEventListener('DOMContentLoaded', function() {
    console.log("Document is ready");
    var myCarousel = document.querySelector('#carouselExampleAutoplaying');
    console.log("Carousel Element:", myCarousel);
    var carousel = new bootstrap.Carousel(myCarousel, {
      interval: 4000,
      ride: 'carousel'
    });
    console.log("Carousel initialized:", carousel);
  });
</script>
{% endblock %}

{% endblock %}

portfolio_site/templates/project.html
{% extends 'base.html' %}

{% block content %}
<div class="container p-1">
  <h2 class="text-primary">{{ request.user }}'s Project Examples</h2>
  <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-interval="3000">
    <div class="carousel-inner">
      {% for image in project_images %}
      <div class="carousel-item {% if forloop.first %}active{% endif %}">
        <h3>Project : {{ image.project.title }}</h3>
        <img src="{{ image.image.url }}" class="d-block w-100" alt="{{ image.name }}">        
      </div>
      {% endfor %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>


<h3 class="text-primary px-2">Projects</h3>
    <hr>
    {% if is_admin or is_intern %}
    <a class="btn btn-link" href="{% url 'add_project' %}">Add New Project</a>
    {% endif %}
        <div class="card-group">
            {% for project in projects %}
            <div class="card">
                <div class="card-body">
                    <h4>{{ project.title }}</h4>
                    <p>{{ project.description }}</p>
                    <a class="btn btn-link" href="{% url 'project_detail' project.id %}">View Project</a>
                </div>
            </div>
            {% endfor %}
        </div>
    <br>
  </div>
    
{% endblock %}

{% block extra_js %}
<script>
  document.addEventListener('DOMContentLoaded', function() {
    console.log("Document is ready");
    var myCarousel = document.querySelector('#carouselExampleAutoplaying');
    console.log("Carousel Element:", myCarousel);
    var carousel = new bootstrap.Carousel(myCarousel, {
      interval: 4000,
      ride: 'carousel'
    });
    console.log("Carousel initialized:", carousel);
  });
</script>
{% endblock %}

portfolio_site/templates/search.html
{% extends 'base.html' %}

{% block title %}Search Results{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="my-4">Search Results for "{{ query }}"</h1>
        
        <div class="list-group">
            {% if portfolios %}
                {% for portfolio in portfolios %}
                    <a href="#" class="list-group-item list-group-item-action">
                        <h5 class="mb-1">{{ portfolio.title }}</h5>
                        <p class="mb-1">Owner: {{ portfolio.user_profile.name }}</p>
                        <a href="{% url 'portfolio_view' portfolio.id %}" class="btn btn-link text-left">View Portfolio</a>
                    </a>
                {% endfor %}
            {% else %}
                <div class="list-group-item">
                    No portfolios found.
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}